StanzaError: Add NoType and NoCondition for -1 values
Previsously static_cast<QXmppStanza::Error::Condition>(-1) was used when
no condition was set (or type). This adds real enum values with that
integer value to avoid undefined behaviour.

Fixes #495.