StanzaError: Remove optional getter/settters for type/condition
The whole QXmppStanza::Error is now used optionally in QXmppStanza, so
type and condition of the error don't need to be optionals as well.

Part of #512.